CREATE TABLE investment_assets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    asset_type VARCHAR(30) NOT NULL,
    name VARCHAR(200) NOT NULL,
    ticker VARCHAR(40),
    isin VARCHAR(20),
    issuer VARCHAR(200),
    currency VARCHAR(3) NOT NULL,
    maturity_date DATE,
    indexer_type VARCHAR(20) NOT NULL,
    indexer_spread VARCHAR(80),
    CONSTRAINT fk_investment_assets_account
        FOREIGN KEY (account_id)
        REFERENCES accounts (id)
);

CREATE TABLE investment_operations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id BIGINT NOT NULL,
    account_id BIGINT NOT NULL,
    operation_type VARCHAR(30) NOT NULL,
    trade_date DATE NOT NULL,
    settlement_date DATE,
    quantity NUMERIC(28, 10),
    unit_price NUMERIC(19, 8),
    gross_amount NUMERIC(19, 2),
    net_amount NUMERIC(19, 2),
    fees NUMERIC(19, 2),
    taxes NUMERIC(19, 2),
    currency VARCHAR(3) NOT NULL,
    notes VARCHAR(1000),
    source_type VARCHAR(30) NOT NULL,
    CONSTRAINT fk_investment_operations_asset
        FOREIGN KEY (asset_id)
        REFERENCES investment_assets (id),
    CONSTRAINT fk_investment_operations_account
        FOREIGN KEY (account_id)
        REFERENCES accounts (id)
);

CREATE TABLE investment_operation_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation_id BIGINT NOT NULL,
    entry_id BIGINT NOT NULL,
    allocated_amount NUMERIC(19, 2),
    CONSTRAINT fk_investment_operation_entries_operation
        FOREIGN KEY (operation_id)
        REFERENCES investment_operations (id),
    CONSTRAINT fk_investment_operation_entries_entry
        FOREIGN KEY (entry_id)
        REFERENCES entries (id),
    CONSTRAINT uk_investment_operation_entries_pair
        UNIQUE (operation_id, entry_id)
);

CREATE INDEX idx_investment_assets_account_id ON investment_assets (account_id);
CREATE INDEX idx_investment_assets_ticker ON investment_assets (ticker);
CREATE INDEX idx_investment_assets_type_name ON investment_assets (asset_type, name);
CREATE INDEX idx_investment_operations_asset_id ON investment_operations (asset_id);
CREATE INDEX idx_investment_operations_account_id ON investment_operations (account_id);
CREATE INDEX idx_investment_operations_trade_date_id ON investment_operations (trade_date, id);
CREATE INDEX idx_investment_operation_entries_operation_id ON investment_operation_entries (operation_id);
CREATE INDEX idx_investment_operation_entries_entry_id ON investment_operation_entries (entry_id);
