CREATE TABLE opening_balances (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    amount NUMERIC(19, 2),
    balance_date DATE,
    CONSTRAINT uk_opening_balances_account UNIQUE (account_id),
    CONSTRAINT fk_opening_balances_account
        FOREIGN KEY (account_id)
        REFERENCES accounts (id)
        ON DELETE CASCADE
);

INSERT INTO opening_balances (account_id, amount, balance_date)
SELECT id, initial_balance, initial_balance_date
FROM accounts
WHERE initial_balance IS NOT NULL OR initial_balance_date IS NOT NULL;

ALTER TABLE accounts DROP COLUMN initial_balance;
ALTER TABLE accounts DROP COLUMN initial_balance_date;
