CREATE TABLE investment_asset_opening_positions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id BIGINT NOT NULL,
    position_date DATE NOT NULL,
    quantity NUMERIC(28, 10) NOT NULL,
    total_cost NUMERIC(19, 2) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    CONSTRAINT uk_investment_asset_opening_positions_asset UNIQUE (asset_id),
    CONSTRAINT fk_investment_asset_opening_positions_asset
        FOREIGN KEY (asset_id)
        REFERENCES investment_assets (id)
        ON DELETE CASCADE
);
