CREATE TABLE brokerage_notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    broker_name VARCHAR(200) NOT NULL,
    broker_cnpj VARCHAR(18) NOT NULL,
    note_number VARCHAR(40) NOT NULL,
    trade_date DATE NOT NULL,
    settlement_date DATE NOT NULL,
    total_costs NUMERIC(19, 2) NOT NULL,
    net_amount NUMERIC(19, 2) NOT NULL,
    imported_at TIMESTAMP NOT NULL,
    original_file_name VARCHAR(255) NOT NULL,
    file_hash VARCHAR(128) NOT NULL,
    net_entry_id BIGINT NOT NULL,
    CONSTRAINT fk_brokerage_notes_net_entry
        FOREIGN KEY (net_entry_id)
        REFERENCES entries (id),
    CONSTRAINT uk_brokerage_notes_broker_note_trade_date
        UNIQUE (broker_cnpj, note_number, trade_date)
);

ALTER TABLE investment_operations ADD COLUMN brokerage_note_id BIGINT;

ALTER TABLE investment_operations ADD CONSTRAINT fk_investment_operations_brokerage_note
    FOREIGN KEY (brokerage_note_id)
    REFERENCES brokerage_notes (id);

CREATE INDEX idx_brokerage_notes_file_hash ON brokerage_notes (file_hash);
CREATE INDEX idx_brokerage_notes_net_entry_id ON brokerage_notes (net_entry_id);
CREATE INDEX idx_investment_operations_brokerage_note_id ON investment_operations (brokerage_note_id);
