CREATE TABLE accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(120) NOT NULL,
    description VARCHAR(300),
    initial_balance NUMERIC(19, 2),
    initial_balance_date DATE
);

CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(120) NOT NULL,
    description VARCHAR(300),
    parent_id BIGINT,
    CONSTRAINT uk_categories_title UNIQUE (title),
    CONSTRAINT fk_categories_parent
        FOREIGN KEY (parent_id)
        REFERENCES categories (id)
);

CREATE TABLE local_user_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(80) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    enabled BOOLEAN NOT NULL,
    CONSTRAINT uk_local_user_accounts_username UNIQUE (username)
);

CREATE TABLE entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    movement_date DATE NOT NULL,
    settlement_date DATE NOT NULL,
    description VARCHAR(200) NOT NULL,
    category_id BIGINT NOT NULL,
    notes VARCHAR(1000),
    amount NUMERIC(19, 2) NOT NULL,
    CONSTRAINT fk_entries_account
        FOREIGN KEY (account_id)
        REFERENCES accounts (id),
    CONSTRAINT fk_entries_category
        FOREIGN KEY (category_id)
        REFERENCES categories (id)
);

CREATE INDEX idx_categories_parent_id ON categories (parent_id);
CREATE INDEX idx_entries_settlement_date_id ON entries (settlement_date, id);
CREATE INDEX idx_entries_account_id ON entries (account_id);
CREATE INDEX idx_entries_category_id ON entries (category_id);
