CREATE TABLE entry_category_suggestion_models (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    trigger_source VARCHAR(20) NOT NULL,
    model_name VARCHAR(120) NOT NULL,
    pipeline_version VARCHAR(80) NOT NULL,
    training_example_count INTEGER,
    label_count INTEGER,
    vocabulary_size INTEGER,
    training_started_at TIMESTAMP NOT NULL,
    completed_at TIMESTAMP,
    failure_message VARCHAR(500),
    model_payload CLOB,
    CONSTRAINT uk_entry_category_suggestion_models_version UNIQUE (version)
);

CREATE INDEX idx_entry_category_suggestion_models_version ON entry_category_suggestion_models (version);
CREATE INDEX idx_entry_category_suggestion_models_status_version
    ON entry_category_suggestion_models (status, version);
