CREATE TABLE federated_user_identities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    local_user_id BIGINT NOT NULL,
    provider VARCHAR(40) NOT NULL,
    subject VARCHAR(200) NOT NULL,
    email VARCHAR(120) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_federated_user_identities_local_user
        FOREIGN KEY (local_user_id)
        REFERENCES local_user_accounts (id),
    CONSTRAINT uk_federated_user_identities_provider_subject UNIQUE (provider, subject)
);

CREATE INDEX idx_federated_user_identities_local_user ON federated_user_identities (local_user_id);
