ALTER TABLE entries
    ADD COLUMN entry_type VARCHAR(20) DEFAULT 'REGULAR';

UPDATE entries
SET entry_type = 'REGULAR'
WHERE entry_type IS NULL;

ALTER TABLE entries
    ALTER COLUMN entry_type SET NOT NULL;

ALTER TABLE entries
    ALTER COLUMN entry_type SET DEFAULT 'REGULAR';

CREATE TABLE entry_transfers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    origin_entry_id BIGINT NOT NULL,
    destination_entry_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    notes VARCHAR(1000),
    CONSTRAINT fk_entry_transfers_origin_entry
        FOREIGN KEY (origin_entry_id)
        REFERENCES entries (id),
    CONSTRAINT fk_entry_transfers_destination_entry
        FOREIGN KEY (destination_entry_id)
        REFERENCES entries (id),
    CONSTRAINT uk_entry_transfers_origin_entry UNIQUE (origin_entry_id),
    CONSTRAINT uk_entry_transfers_destination_entry UNIQUE (destination_entry_id),
    CONSTRAINT chk_entry_transfers_distinct_entries CHECK (origin_entry_id <> destination_entry_id)
);

CREATE INDEX idx_entries_entry_type ON entries (entry_type);
CREATE INDEX idx_entry_transfers_origin_entry_id ON entry_transfers (origin_entry_id);
CREATE INDEX idx_entry_transfers_destination_entry_id ON entry_transfers (destination_entry_id);
